### PR TITLE
Bugfix | correct ﻿domain name wiki.froth.zone

### PR DESCRIPTION
**Pull request by ph00lt0**
You doubled https

### CODE REVIEW

**Comment by ManeraKai** [comment]
That's not a problem on our side. Check the list on Wikiless: https://wikiless.org/instances.json there shouldn't be `https://` like the others.
Please open an issue on https://codeberg.org/orenom/wikiless to inform them. It will get automatically updated from our side.

**Comment by EdwardLangdon** [comment]
As this should be fixed by Wikiless maintainers we cannot do anything. So, Closing this PR.

**Comment by ph00lt0** [comment]
I don't think it's necessary work in the wikiless, seems you need better checking of whether the instance already has https://

**Comment by ManeraKai** [comment]
> You break your own project by not validating input, yeah right! Sounds like the right way of doing things....

It really doesn't break rather just a list feature and it doesn't get automatically updated unless you press `Update Instances` in your settings. It get updated every new release, but we will be there already and active if a problem happens as we're literally releasing a new version. I really trust the lists maintainers the same way I trust the instances' owners. It's not that easy to validate. I can go far and even connect to each instance to see if it's online or not, to see if it's really running that service or not. It's not just about a valid url. This job is really for the lists maintainers rather than our job. And I trust them. Any problem happens, we contact them or anyone and they'll correct it from their side.

> I am not a codeberg user so can't help you with that.

No worries! I have one.

**Comment by ManeraKai** [comment]
Created it: https://codeberg.org/orenom/Wikiless/pulls/60

**Comment by ph00lt0** [comment]
I think it could just easily be prevented by having input validation, generally that is good practice ;)

**Comment by ManeraKai** [comment]
tbh you have a point. I will make some simple validation but not as far as connecting to each instance to check it.

**Comment by ManeraKai** [comment]
Sorry, I commented on the wrong issue. I Added it before 2 days. I'll improve the script more in the future so it will be more reliable.
commit: https://github.com/libredirect/libredirect/commit/ec3089c8bcb58fe0bd2a6e71c928c711bac967ec

**Pull request closed without merging**
