### PR TITLE
Fixed misleading Icon

### PR DESCRIPTION
**Pull request by EdwardLangdon**

### CODE REVIEW

**Comment by EdwardLangdon** [comment]
@ManeraKai I fixed things. But the Image resolution seems to big in the README.md file.

**Comment by EdwardLangdon** [comment]
The Current commit resized the image to 312*100. If you can provide the Dimensions I could fix it.

**Comment by ManeraKai** [comment]
> If you can provide the Dimensions I could fix it.

Just look at the dimensions of the other badges, you can resize the badge by writing html rather than md. ex:

**Comment by EdwardLangdon** [comment]
Do you mean writing HTML in markdown file ?

**Comment by ManeraKai** [comment]
Yeah, you either have that option if you want. I prefer it since we may need a higher resolution images.

**Pull request merged**
