### PR TITLE
Update pt_BR messages.json

### PR DESCRIPTION
**Pull request by marcelocripe**
Please accept the pt_BR translation of the messages.json file.

The file that has the most recent translation is at this URL:
https://github.com/marcelocripe/LibreDirect/blob/main/Libre_Direct_messages_pt_BR.json

I appreciate you creating, maintaining and updating LibreDirect .

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese)

- - - - -

Por favor, aceite a tradução para pt_BR do arquivo messages.json.

O arquivo que possui a tradução mais recente está neste URL:
https://github.com/marcelocripe/LibreDirect/blob/main/Libre_Direct_messages_pt_BR.json

Eu agradeço por você criar, manter e atualizar o LibreDirect .

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil)

### CODE REVIEW

**Comment by EdwardLangdon** [comment]
@marcelocripe Is the PR #404 of yours invalid now or we should merge that first and then this next ?

**Comment by EdwardLangdon** [comment]
Will check this PR later and approve. Thanks for your Contribution.

Final Confirmation, This is the PR to be considered, right ?

**Comment by marcelocripe** [comment]
The most recent "Pull Requests" always has the highest number.
The order I made (PR #404 opened 29 days ago) is outdated as it had PR 408 (https://github.com/libredirect/libredirect/issues/408) which changed all the "messages.json" files ( Fixed typo #408 13 days ago).

Please if you can copy the file https://github.com/marcelocripe/LibreDirect/blob/main/Libre_Direct_messages_pt_BR.json or this we will make sure it is the latest translation and in the standards of the latest update of the "messages" file .json".

I apologize, GitHub crashes a lot on an old computer with a bad internet connection.

- - - - -

O "Pull Requests" mais recente possui sempre o maio número.
O pedido que eu fiz (PR #404 opened 29 days ago) está desatualizado, pois teve o PR 408 (https://github.com/libredirect/libredirect/issues/408) que alterou todos os arquivos "messages.json" (Fixed typo #408 13 days ago).

Por favor, se você puder copiar o arquivo https://github.com/marcelocripe/LibreDirect/blob/main/Libre_Direct_messages_pt_BR.json ou este teremos certeza de que é a tradução mais recente e nos padrões da atualização mais recente do arquivo "messages.json". 

Eu peço desculpas, o GitHub trava muito em um computador antigo e com conexão com a internet ruim.
[Libre_Direct_messages_marcelocripe_pt_BR_26-08-2022_json.zip](https://github.com/libredirect/libredirect/files/9438094/Libre_Direct_messages_marcelocripe_pt_BR_26-08-2022_json.zip)

**Comment by EdwardLangdon** [comment]
Fine will check and merge your PR. Once again thanks for your contribution.

**Comment by EdwardLangdon** [comment]
@marcelocripe Can you fix the conflict in this PR and close PRs that are unnecessary because of this PR ?

**Comment by marcelocripe** [comment]
"@marcelocripe Can you fix the conflict in this PR and close PRs that are unnecessary because of this PR ?"
Perdão, Edward, mas eu ainda não seu cancelar um PR. Eu posso tentar fazer isso agora.

**Comment by EdwardLangdon** [comment]
As you closed the PR. I cannot tell the conflicts because they are gone.

**Pull request closed without merging**
