### PR TITLE
Automatic fetching of piped instances

### PR DESCRIPTION
**Pull request by BobIsMyManager**
I have done some of the work but unfortunately I cannot figure out why no piped instances are being shown in the UI even though I have tried my best to replicate what happens with invidious with piped. I know the error is with the extension itself looking for instances in the wrong place. If you could commit a fix or explain how it is done, I would be very grateful.

### CODE REVIEW

**Comment by ManeraKai** [comment]
Some instances don't have a web interface. Just an API. Also, some of them have weird naming schemes I remember. @EdwardLangdon

**Comment by EdwardLangdon** [comment]
`src/assets/javascripts/helpers/youtube/youtube.js` - This is the place where Piped Instances are listed. The reason why Piped Instances are listed in `youtube.js` is that `data.json` is meant to be updated by the python script for Auto Updating Instances and cannot be excluded in the Script, AFAIK. 

The Instances listed maintained by project maintainers of Piped are API links which is specifically meant to use the those instances for fetching Data in the Official Frontend with inception of not violating AGPLv3 and not delivering Malicious JS. You can get more info here too - https://github.com/TeamPiped/Piped/issues/787#issuecomment-1030682027. So, That's why you don't see the direct link for those instances instead API links of those Instances.

So far, I am updating those Instances in the source I listed in the First line. I added New Instances and released in v 1.5.7 but I don't see it in my Browser though. I am currently checking it if it is doing anything with your PR.

@ManeraKai @BobIsMyManager Can you see the Piped Instances added by me in your Browser ?

**Comment by ManeraKai** [comment]
> and cannot be excluded in the Script, AFAIK.

Indeed, They will be overwritten.

**Comment by EdwardLangdon** [comment]
So, I think we can close this PR.

**Pull request closed without merging**
