### PR TITLE
drop all instances from 'alefvanoon.xyz'

### PR DESCRIPTION
**Pull request by dmarto**
The domain has expired and is currently for sale at auction.

### CODE REVIEW

**Comment by EdwardLangdon** [comment]
As you can read in the [FAQ page](https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from). Instances are from Official list of Instances. It's better you ask or submit the PR to respective projects. 

Thanks for Chiming in and contributing to Libredirect. We appreciate your work. But we can't approve of this PR. So, I am closing it.

**Comment by dmarto** [comment]
My bad, I was thinking that maybe 'alefvanoon.xyz' as a platform from one of the authors/maintainers of this plugin, may be considered in a more special way (or with higher priority).

On top of that, the fact that it is not simply 404ring, but redirecting to a "unknown" 3rd party page, that is in the "business" of auctioning expired/dropped domains i.e not the most ethical or privacy conscious place.

Anyway, thank you for the suggestion, but I will just maintain my own instance file and point the add-on there.

**Comment by EdwardLangdon** [comment]
Alefvanoon.xyz is the domain of @alefvanoon who has been busy for a while IRL.

He might have forget to renew the domain. AFAIK, he is moving his services to tokhmi.xyz and Alefvanoon.xyz is cloudflare which is disabled by default. So, I think it doesn't make any sense further.

>I will just maintain my own instance file and point the add-on there.

For what ? 

IMO, It is inefficient and waste of time. I would suggest sticking to using Instances listed in the Official Projects.

**Comment by dmarto** [comment]
If it was disabled by default, I would agree with you, but it is not, and after every instances update it is again enabled (if I disabled it manually), I got tired of all that, thus this PR.

**Comment by EdwardLangdon** [comment]
Well, I am not sure if it does come back in v2.0. Weird Issue. I would suggest backing up settings, Reset or Reinstall Libredirect and import settings back. Do if you wish at your own cost.

**Comment by dmarto** [comment]
Indeed, I may have encountered a bug. At the moment, my own "fix" costs me nothing, I just threw few lines of code that intercept the request and drop any lines with the domain from the response.

Anyway, thanks for your time and suggestions :)

**Pull request closed without merging**
