### PR TITLE
Add thekitty.zone services

### PR DESCRIPTION
**Pull request by hardcore-sushi**
Adds services provided by @11Tuvork28: https://thekitty.zone/services
Also fixes "invidio.xamh.de" to the new domain.

### CODE REVIEW

**Comment by 11Tuvork28** [comment]
Hey @hardcore-sushi, thanks for taking the time looking through my site and doing this PR. Its something I wanted to do anyways but honestly at moment I have no energy for this, one thing to note is that except for invidious none the hosted services are listed in the respective project  due the afore mentioned reason. 
Means the world to me!

**Comment by hardcore-sushi** [comment]
Oh, so I have to open a PR on the different lists of instances instead?

**Comment by ManeraKai** [comment]
Yep exactly.

**Comment by hardcore-sushi** [comment]
@11Tuvork28 Do you agree that I do it?

**Comment by 11Tuvork28** [comment]
Yeah go ahead :) Dont have time right now to help

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by hardcore-sushi** [comment]
@ManeraKai Perhaps we could warn other contributors with a message in `CONTRIBUTING.md` or in the PR template. Or maybe I'm the only one who's stupid enough to try to change an automatically generated file.

**Comment by ManeraKai** [comment]
In the next release we'll have the instances list in a different repository and we will document on how to contribute to it.

**Pull request closed without merging**
