### PR TITLE
Automatic send instance fetching

### PR DESCRIPTION
**Pull request by BobIsMyManager**

### CODE REVIEW

**Comment by ManeraKai** [comment]
I've submitted a PR on your [repo](https://github.com/BobIsMyManager/libredirect/pull/1)

**Comment by BobIsMyManager** [comment]
> I've submitted a [PR](https://github.com/BobIsMyManager/libredirect/pull/1) on your Repo.

It is possible for you to directly commit to my send branch as I opened a pull request allowing for that

**Comment by BobIsMyManager** [comment]
Can you hold off from merging this? After doing some testing I realised things are not working as intened

**Comment by BobIsMyManager** [comment]
For some reason libredirect is able to fetch remote instances (if you set your `apiEndpoint` to [this](https://gist.githubusercontent.com/BobIsMyManager/3cb69c7e37703f7b657ec33281636401/raw/8fa1247f8c4fb1d52fe32b2ef6cebdb4b4105101/data.json), but it doesnt seem to be able to get data locally 

https://user-images.githubusercontent.com/70704875/162534636-a4c0b647-9f5c-454c-aeed-84368bcfb89e.mov

**Comment by ManeraKai** [comment]
I'll see what's wrong.

**Comment by ManeraKai** [comment]
It's working fine on my side. Try to reload the extension for it to load the new local file.

**Comment by BobIsMyManager** [comment]
Whenever I try to reload the extension the firefox window closes and doesn't re-open. But if you think its working fine, go ahead and merge the pr.

**Comment by ManeraKai** [comment]
> Whenever I try to reload the extension the firefox window closes and doesn't re-open. But if you think its working fine, go ahead and merge the pr.

It closes the settings page. Just open any other window like https://google.com and it will not close it the window rather that just the settings tab

**Comment by BobIsMyManager** [comment]
> > Whenever I try to reload the extension the firefox window closes and doesn't re-open. But if you think its working fine, go ahead and merge the pr.
> 
> It closes the settings page. Just open any other window like [google.com](https://google.com) and it will not close it the window rather that just the settings tab

It still doesn't seem to get the send instances from the local `data.json`

**Pull request merged**
