### PR TITLE
Fixes typo on the Search page

### PR DESCRIPTION
**Pull request by Dyras**
Hello. This fixes a typo on the Search page.

it's full potential -> its full potential

### CODE REVIEW

**Comment by ManeraKai** [comment]
It's correct. You can't say `To use Search to it is full potential`

**Comment by IronMaltese** [comment]
image

**Comment by Dyras** [comment]
@ManeraKai Yes? It was wrong before and this fixes it.

**Comment by ManeraKai** [comment]
No. It was correct from the beginning imo.

**Comment by silverwings15** [comment]
this is how it is in 1.6.0 

image

so the PR is correct

**Comment by Dyras** [comment]
@ManeraKai No problem man, keep up the good work with this awesome addon :)

**Pull request merged**
