### PR TITLE
Add invidious.fdn.fr

### PR DESCRIPTION
**Pull request by TotalCaesar659**
https://invidious.fdn.fr

### CODE REVIEW

**Comment by ManeraKai** [comment]
LibRedirect doesn't work like Privacy Redirect. The list is automated and fetched from the official lists. Add your instance to https://api.invidious.io/ and it will be fetched here automatically.

**Comment by TotalCaesar659** [comment]
Done, thanks.

**Comment by ManeraKai** [comment]
Done?!

**Comment by TotalCaesar659** [comment]
Iv'e don PR [here](https://github.com/iv-org/documentation/pull/212), what do you mean?

**Comment by ManeraKai** [comment]
Sorry, I thought you meant by `Done` that it was submitted and approved too from their side. I even checked the list 😅

**Comment by TotalCaesar659** [comment]
Ah. got it. Unfortunately, I'm not so almighty :-)

**Pull request closed without merging**
