### PR TITLE
proxitok

### PR DESCRIPTION
**Pull request by BobIsMyManager**
Once again even after reloading the extention, it still refuses to load instances and I still can't figure out if something is missing, or if there is an issue with my machine.

### CODE REVIEW

**Comment by ManeraKai** [comment]
At which path do you run the python script?
btw no need for Bs4. Here's is it in raw markdown: https://raw.github.com/wiki/pablouser1/ProxiTok/Public-instances.md

**Comment by BobIsMyManager** [comment]
> At which path do you run the python script?

At the root of the repo
> btw no need for Bs4. Here's is it in raw markdown: [raw.github.com/wiki/pablouser1/ProxiTok/Public-instances.md](https://raw.github.com/wiki/pablouser1/ProxiTok/Public-instances.md)

Ok, done

**Comment by ManeraKai** [comment]
Add this line
```js
redirects.proxiTok = dataJson.proxiTok;
```
here:
image
This line will fetch the results from the `data.json` file,

**Comment by BobIsMyManager** [comment]
I have tried this before, and for some reason when I do this I still dont get any instances popup, instead I just get 2 instance fields

image

**Comment by ManeraKai** [comment]
Does it give any error in the console?

**Comment by BobIsMyManager** [comment]
image

**Comment by ManeraKai** [comment]
oh I know. Add this line to the python file. The same happened with send fetching.
```python
proxiTokList['tor'] = []
```
between those two lines: https://github.com/BobIsMyManager/libredirect/blob/master/src/instances/get_instances.py#L43-L44=

**Comment by BobIsMyManager** [comment]
Well that fixed it! I was surprised as I didnt think that would effect it, especially since it works fine without i2p

**Comment by ManeraKai** [comment]
It's working fine without i2p because there's no function calling it like what's happening with tor here: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/tiktok.js#L143=

**Comment by BobIsMyManager** [comment]
Ah, should that be removed then if there are no instances for it? Or should there be i2p support for every instance aswell if the user has their own i2p instance they want to use.

**Comment by ManeraKai** [comment]
there should be support for even i2p, but almost no one uses it right now. We'll do this later.

**Comment by ManeraKai** [comment]
I didn't mean to delete it 😅

**Comment by BobIsMyManager** [comment]
Well I dont think its needed for everyone to share as its generated on everyoned local machines, right?

**Comment by ManeraKai** [comment]
yep, you're right.

I'll merge now.

**Comment by BobIsMyManager** [comment]
Well the i2p intergration for all instances is still a thing, but that derserves its own pull request.

**Comment by ManeraKai** [comment]
It should be for all serivces. not just i2p so as you said: a whole PR.

**Comment by BobIsMyManager** [comment]
> It should be for all serivces. not just i2p so as you said: a whole PR.

Lets continue this discussion on matrix

**Comment by ManeraKai** [comment]
btw thanks @BobIsMyManager! This really helps accelerate the work!

**Comment by BobIsMyManager** [comment]
Life is too short for manual instance fetching ;)

**Pull request merged**
