### PR TITLE
add i18n + German translation

### PR DESCRIPTION
**Pull request by realpixelcode**
This PR adds i18n capability and a German translation. 

There's just 1 minor issue: In line 102 of `common.js` the string `Toggle All` needs to be translated. I inserted a `data-localise="__MSG_toggleAll__"` HTML property into the element just like with a regular HTML file. For some reason, however, this string isn't translated by `localise.js`, most likely due to the string not having been inserted at `localise.js'` runtime yet.

Unfortunately, I do not know how to fix this.

### CODE REVIEW

**Comment by ManeraKai** [comment]
Use `browser` rather than `chrome`. This is to support both firefox and chrome:
https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/general.js#L2=

**Comment by ManeraKai** [comment]
YouTube, Twitter, Wikipedia and more all have translations in Arabic; ex:
YouTube => يوتيوب
Twitter => تويتر
Wikipedia => ويكيبيديا
They should be included too.

**Comment by ManeraKai** [comment]
Still there's one `chrome.` in `background.js`

**Comment by realpixelcode** [comment]
> Use `browser` rather than `chrome`. This is to support both firefox and chrome: https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/general.js#L2=

Ok, did that in both modified JS files.

>YouTube, Twitter, Wikipedia and more all have translations in Arabic

I think that can wait until there's an actual Arabic translation 😅 (also LibRedirect would need to support RTL first)

> Still there's one `chrome.` in `background.js`

Ok, changed that too (wasn't mine though).

**Comment by ManeraKai** [comment]
I'm Arabian and I will translated it to Arabic before merging. We'll support rtl before merging this PR too.

**Comment by realpixelcode** [comment]
Oh, nice, then I'll do that real quick

**Comment by realpixelcode** [comment]
So, I'm finished with adding the services' names to i18n ☺️

**Comment by ManeraKai** [comment]
btw FIY, you can download firefox in your language form here: https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/ and then set a custom path for web-ext e.g:
```
web-ext run --browser-console --firefox=/home/esmail/Downloads/firefox/firefox
```

**Comment by ManeraKai** [comment]
Found a way to fix the `Toggle All` it's happening because they're some `async` requests. I'll send a PR now.

**Comment by ManeraKai** [comment]
Also, Don't translate invidious settings by yourself. Get them form Invidious' Weblate Page: https://hosted.weblate.org/projects/invidious/

**Comment by ManeraKai** [comment]
Strings that aren't translated in e.g Piped shouldn't be translated too.

**Comment by realpixelcode** [comment]
Okay, I'll check what's different and update it

**Comment by realpixelcode** [comment]
I just updated the i18n strings of Invidious and Piped.

**Comment by ManeraKai** [comment]
Merge my commit as it has fixed, translation, and rtl support

**Comment by realpixelcode** [comment]
> Merge my commit as it has fixed, translation, and rtl support

Should I do that? Where do I find your commit?

**Comment by ManeraKai** [comment]
It's in your repo: https://github.com/Pixelcode-LibRedirect/libredirect/pull/1

**Comment by ManeraKai** [comment]
Tor isn't translated. It has an Arabic translation: https://ar.wikipedia.org/wiki/%D8%AA%D9%88%D8%B1_(%D8%B4%D8%A8%D9%83%D8%A9)

This one too, `Frontend` in pixiv:
image

**Comment by realpixelcode** [comment]
Oh, right, I'll correct that quickly

**Comment by realpixelcode** [comment]
So I've just corrected it. What does `pixiv萌え` mean in the first place though?

**Comment by ManeraKai** [comment]
It means pixivMoe If I remember.

**Comment by ManeraKai** [comment]
Arabic translation:
```json
    "tor": {
      "message": "تور",
      "description": "used in imgur.html"
    },

    "pixivMoe": {
      "message": "pixiv萌え",
      "description": "used in pixiv.html"
    },
```

**Comment by realpixelcode** [comment]
yeah, seems to: https://en.wikipedia.org/wiki/Moe_(slang)

**Comment by ManeraKai** [comment]
oh, I meant to translate the word `Frontend` that is underlined by a greenline. Not `pixivMoe`, but keep `pixivMoe`, we may even add the other frotnends if they got their names translated.

**Comment by realpixelcode** [comment]
> oh, I meant to translate the word `Frontend` that is underlined by a greenline

oh right

**Comment by ManeraKai** [comment]
Looks Good to me. I'll merge it. Is there anything you have in mind?

**Comment by realpixelcode** [comment]
For now we are done with i18n, I think

**Comment by ManeraKai** [comment]
Perfect! I just can't say but thank you! You really stepped in in the right time. It's such a huge help to be a PR rather than an issue.

**Comment by realpixelcode** [comment]
I'm always happy to help :)

**Pull request merged**
